### PR TITLE
Feature(auth)

### PR DESCRIPTION
**Pull request by SpBills**
Added required auth protection on every path.

### CODE REVIEW

**Comment by Alec-WAM** [comment]
Could we also add an email list check to the route as well? Because giving any google account access I feel like is not a great idea. We also could lock down the messages to the specific toEmail route as well. That way other users can't see other users commendations

**Comment by SpBills** [comment]
> Could we also add an email list check to the route as well? Because giving any google account access I feel like is not a great idea. We also could lock down the messages to the specific toEmail route as well. That way other users can't see other users commendations

This actually doesn't make sense to me. You cannot make a JWT unless you sign in via the login button, and the login button only allows cedarville.edu addresses that are present in the excel sheet. So, the fact that we create the JWT in the first place should be a good enough indicator that the email is a cedarville.edu email.

Am I misunderstanding?

**Comment by SpBills** [comment]
@Alec-WAM

**Comment by SpBills** [comment]
I can add a check on the backend that decodes the JWT and checks for a CU email.

**Comment by Alec-WAM** [comment]
> > Could we also add an email list check to the route as well? Because giving any google account access I feel like is not a great idea. We also could lock down the messages to the specific toEmail route as well. That way other users can't see other users commendations
> 
> This actually doesn't make sense to me. You cannot make a JWT unless you sign in via the login button, and the login button only allows cedarville.edu addresses that are present in the excel sheet. So, the fact that we create the JWT in the first place should be a good enough indicator that the email is a cedarville.edu email.
> 
> Am I misunderstanding?

My understanding was that anyone could place a JWT google token in the Bearer token and the tokenCheck would confirm it and allow it. Also if we wanted to get the email from the JWT anyway to lock down the view route as well we could add that feature to make sure it is on our list as well

**Comment by Alec-WAM** [comment]
> > > > Could we also add an email list check to the route as well? Because giving any google account access I feel like is not a great idea. We also could lock down the messages to the specific toEmail route as well. That way other users can't see other users commendations
> > > 
> > > 
> > > This actually doesn't make sense to me. You cannot make a JWT unless you sign in via the login button, and the login button only allows cedarville.edu addresses that are present in the excel sheet. So, the fact that we create the JWT in the first place should be a good enough indicator that the email is a cedarville.edu email.
> > > Am I misunderstanding?
> > 
> > 
> > My understanding was that anyone could place a JWT google token in the Bearer token and the tokenCheck would confirm it and allow it. Also if we wanted to get the email from the JWT anyway to lock down the view route as well we could add that feature to make sure it is on our list as well
> 
> For that latter part, I have a nifty function on the backend that checks to see if you can "read" the page, and if not replies with a 403. The frontend displays the following when it gets that:
> 
> image

What I kinda meant was we check the current JWT's email and if its alecmathisen@cedarville.edu then only allow the /commendations/alecmathisen@cedarville.edu to return for me but if the current user's JWT email is "sbill@cedarville.edu" and they try and hit /commendations/alecmathisen@cedarville.edu then return a 403

**Comment by SpBills** [comment]
> > > > > Could we also add an email list check to the route as well? Because giving any google account access I feel like is not a great idea. We also could lock down the messages to the specific toEmail route as well. That way other users can't see other users commendations
> > > > 
> > > > 
> > > > This actually doesn't make sense to me. You cannot make a JWT unless you sign in via the login button, and the login button only allows cedarville.edu addresses that are present in the excel sheet. So, the fact that we create the JWT in the first place should be a good enough indicator that the email is a cedarville.edu email.
> > > > Am I misunderstanding?
> > > 
> > > 
> > > My understanding was that anyone could place a JWT google token in the Bearer token and the tokenCheck would confirm it and allow it. Also if we wanted to get the email from the JWT anyway to lock down the view route as well we could add that feature to make sure it is on our list as well
> > 
> > 
> > For that latter part, I have a nifty function on the backend that checks to see if you can "read" the page, and if not replies with a 403. The frontend displays the following when it gets that:
> > image
> 
> What I kinda meant was we check the current JWT's email and if its [alecmathisen@cedarville.edu](mailto:alecmathisen@cedarville.edu) then only allow the /commendations/alecmathisen@cedarville.edu to return for me but if the current user's JWT email is "[sbill@cedarville.edu](mailto:sbill@cedarville.edu)" and they try and hit /commendations/alecmathisen@cedarville.edu then return a 403

Oh, whoops. Yeah, that's possible! I can get that done for you.

**Comment by SpBills** [comment]
> > > > > Could we also add an email list check to the route as well? Because giving any google account access I feel like is not a great idea. We also could lock down the messages to the specific toEmail route as well. That way other users can't see other users commendations
> > > > 
> > > > 
> > > > This actually doesn't make sense to me. You cannot make a JWT unless you sign in via the login button, and the login button only allows cedarville.edu addresses that are present in the excel sheet. So, the fact that we create the JWT in the first place should be a good enough indicator that the email is a cedarville.edu email.
> > > > Am I misunderstanding?
> > > 
> > > 
> > > My understanding was that anyone could place a JWT google token in the Bearer token and the tokenCheck would confirm it and allow it. Also if we wanted to get the email from the JWT anyway to lock down the view route as well we could add that feature to make sure it is on our list as well
> > 
> > 
> > For that latter part, I have a nifty function on the backend that checks to see if you can "read" the page, and if not replies with a 403. The frontend displays the following when it gets that:
> > image
> 
> What I kinda meant was we check the current JWT's email and if its [alecmathisen@cedarville.edu](mailto:alecmathisen@cedarville.edu) then only allow the /commendations/alecmathisen@cedarville.edu to return for me but if the current user's JWT email is "[sbill@cedarville.edu](mailto:sbill@cedarville.edu)" and they try and hit /commendations/alecmathisen@cedarville.edu then return a 403

I can do this once the frontend fetching & display is done.

**Comment by SpBills** [comment]
I actually just got a really nice implementation of it done. The backend now decrypts your key and takes the email from it.

**Comment by SpBills** [comment]
`/commendation/one` will only return if I am logged in.

**Comment by Alec-WAM** [comment]
> I actually just got a really nice implementation of it done. The backend now decrypts your key and takes the email from it.

Genius! Yeah that is super smart and I didn't even think of that

**Comment by Alec-WAM** [comment]
This look done to me. Aiden is working on some stuff with the list displaying and I want to get things done on the display side while we can easily grab them by email then I will pull this in!

**Comment by SpBills** [comment]
Alright, I added the backend checking of the JWT. Now when you log in, you really shouldn't be able to authenticate successfully unless you have a cedarville.edu email that exists in the spreadsheet.

**Pull request merged**
